name: pro_ecommerce
description: "A new Flutter project."

publish_to: "none"

version: 2.1.0 #1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_ui_auth: ^1.16.0
  firebase_ui_firestore: ^1.7.0

  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.16
  go_router: ^14.6.2
  intl: ^0.19.0
  rxdart: ^0.28.0
  shared_preferences: ^2.3.3
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.6.1
  force_update_helper: ^0.1.5
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #mocktail: ^1.0.4
  mockito: ^5.0.16
  random_string: ^2.3.1
  flutter_lints: ^5.0.0
  # a tool for running code generators
  build_runner: ^2.4.13
  # the code generator
  riverpod_generator: ^2.6.3
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.6.3
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.7.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
